### ISSUE TITLE
Requesting ability to change background colors, and default to all photos album

### ISSUE THREAD

**Issue by hyouuu** [maximbilan/SwiftAssetsPickerController#1]
Firstly thanks for the controller! I love how simple the code structure is, and would love to see it make appearance more customizable, as well as able to default to the "All Photos" album when opened.

**Comment by maximbilan** [comment]
Hi,

Thanks for using the control. Sure, it would be great if the control will be customizable. Unfortunately now I'm busy with another projects, so if you can do this changes and will do pull request, I will be really appreciate.

Thanks,
Maxim
